# docker-compose.yml
version: "3.7"
services:
  postgres:
    image: postgres:11
    ports:
      - 5432:5432
    volumes:
      - ./sampledata.sql:/docker-entrypoint-initdb.d/1-init.sql
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust